version: '3'
services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - net
  tomcat:
    container_name: tomcat
    image: tomcat:8.0-alpine
    build:
     context: ./tomcat
     dockerfile : Dockerfile.alp
    ports:
     - "8081:8080"
    networks:
     - net
networks:
  net:

